CREATE TABLE [dbo].[Api]
(
  [Id] INT NOT NULL PRIMARY KEY,
  RequestBody NVARCHAR(100) NOT NULL,
  ResponseBody NVARCHAR(100) NOT NULL,
  [Status] NVARCHAR(100) NOT NULL CONSTRAINT DF_Api_Status DEFAULT '200',
  CreatedOn DATETIME NOT NULL CONSTRAINT DF_Api_CreatedOn DEFAULT GETDATE(),
  ModifiedOn DATETIME NOT NULL CONSTRAINT DF_Api_ModifiedOn DEFAULT GETDATE()
)
