traces
| where customDimensions.Application startswith "FileIt"
| where isnotempty(customDimensions.InvocationId)
| extend ChicagoTime = datetime_utc_to_local(timestamp, 'America/Chicago')
| extend EventIdDynamic = parse_json(tostring(customDimensions.EventId))
| extend Event = coalesce(
	tostring(customDimensions.EventIdName),
	tostring(customDimensions["EventId.Name"]),
	tostring(EventIdDynamic.Name),
	tostring(customDimensions.EventName),
	tostring(customDimensions.EventId)
)
| project ChicagoTime
, InvocationId = customDimensions.InvocationId
, CorrelationId = customDimensions.CorrelationId
, Event
, SourceContext = customDimensions.SourceContext
, Application = customDimensions.Application
, Version = customDimensions.ApplicationVersion
, Infrastructure = customDimensions.InfrastructureVersion
, Message = message