CREATE TABLE [dbo].[SimpleRequestLog]
(
  [Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  Environment NVARCHAR(100) NOT NULL,
  Host NVARCHAR(100) NOT NULL,
  Agent NVARCHAR(100) NOT NULL,
  BlobName NVARCHAR(100) NOT NULL,
  ClientRequestId NVARCHAR(100) NOT NULL,
  Comment NVARCHAR(100) NULL,
  ApiId INT NOT NULL,
  [Status] NVARCHAR(100) NOT NULL,
  CreatedOn DATETIME2 NOT NULL,
  ModifiedOn DATETIME2 NOT NULL
)
